export const degree_major: Record<string, string[]> = {
  "Bachelor of Applied Science": ["Information Technology"],
  "Bachelor of Architecture": ["None"],
  "Bachelor of Arts": [
    "Asian Studies",
    "Dance",
    "English",
    "Geography",
    "History",
    "International Affairs",
    "Modern Language and Culture",
    "Theatre and Performance Studies",
  ],
  "Bachelor of Business Administration": [
    "Accounting",
    "Economics",
    "Entrepreneurship",
    "Finance",
    "Hospitality Management",
    "Information Security and Assurance",
    "Information Systems",
    "Management",
    "Marketing",
    "Professional Sales",
  ],
  "Bachelor of Fine Arts": ["Art", "Digital Animation"],
  "Bachelor of Music": ["None"],
  "Bachelor of Music Education": ["None"],
  "Bachelor of Science": [
    "Aerospace Engineering",
    "Anthropology",
    "Biochemistry",
    "Biology",
    "Chemistry",
    "Civil Engineering",
    "Computer Engineering",
    "Computer Game Design and Development",
    "Computer Science",
    "Construction Management",
    "Criminal Justice",
    "Cybersecurity",
    "Data Science and Analytics",
    "Early Childhood Education",
    "Electrical Engineering",
    "Electrical Engineering Technology",
    "Elementary Education",
    "English Education",
    "Environmental Engineering",
    "Environmental Science",
    "Exercise Science",
    "Geospatial Sciences",
    "Health and Physical Activity Leadership",
    "History Education",
    "Human Services",
    "Industrial Engineering Technology",
    "Industrial and Systems Engineering",
    "Information Technology",
    "Integrated Health Science",
    "Interactive Design",
    "Interdisciplinary Studies",
    "Journalism and Emerging Media",
    "Learning, Design, and Technology",
    "Mathematics",
    "Mechanical Engineering",
    "Mechanical Engineering Technology",
    "Mechatronics Engineering",
    "Media and Entertainment",
    "Middle Grades Education",
    "Nursing",
    "Organizational and Professional Communication",
    "Physics",
    "Political Science",
    "Psychology",
    "Public Health",
    "Public Relations Degree",
    "Secondary Education",
    "Sociology",
    "Software Engineering",
    "Sport Management",
  ],
  "Master of Accounting": ["None"],
  "Master of Arts": [
    "American Studies",
    "Art and Design",
    "Integrated Global Communication",
    "Professional Writing",
    "Teaching",
  ],
  "Master of Business Administration": ["None"],
  "Master of Education": [
    "Leadership",
    "Elementary and Early Childhood Education",
    "Instructional Technology",
    "Literacy Education",
    "Secondary and Middle Grades Education",
    "Special Education",
    "Teacher Leadership and Educational Leadership",
    "Teaching English to Speakers of Other Languages",
  ],
  "Master of Public Administration": ["None"],
  "Master of Science": [
    "Intelligence",
    "Chemical Sciences",
    "Civil Engineering",
    "Computer Science",
    "Conflict Management",
    "Construction Management",
    "Criminal Justice",
    "Cybersecurity",
    "Data Science and Analytics",
    "Digital Financial Technologies (Fintech)",
    "Electrical and Computer Engineering",
    "Engineering Management",
    "Exercise Science",
    "Healthcare Management and Informatics",
    "Information Systems",
    "Information Technology",
    "Integrative Biology",
    "Intelligent Robotic Systems",
    "International Policy Management",
    "Mechanical Engineering",
    "Nursing - Family Nurse Practitioner",
    "Nursing - Leadership",
    "Prosthetics and Orthotics",
    "Software Engineering",
    "Systems Engineering",
  ],
  "Master of Social Work": ["None"],
  None: ["None"],
};

export const degreeOptions = Object.keys(degree_major).map((degree) => ({
  label: degree,
  value: degree,
}));

export const majorOptions = (
  degree: string,
): { label: string; value: string }[] => {
  return degree_major[degree]?.map((major) => ({
    label: major,
    value: major,
  }));
};
